"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7te9pbvyse-4m(=o)u-(#j8a@72%0pz5qse#aw)l&uh%!ld)p5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qshop',
        'USER': 'root',
        'PASSWORD': '111111',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'mydatabase',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

# STATIC_ROOT = os.path.join(BASE_DIR,'static')
## 媒体资源
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'static')

from alipay import AliPay
## 公钥的配置
alipay_public_key_string="""-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy1o2kzDLr8rXWVgtQ2HcaCXwlFyskx7V5PlWkRqqIqgVQQ7kiPw4Ru9PWou3fA5hBWCNQmJEgIBfGukdqoeitXcft1K5U5/gEOrUL8dqBf/VsN4iAwzptgfDXnC6UGz0NmOWihi6LtXftds7uMVNYAXHs3vf9TgJJusehVpkT7Evf+46VAKh7TnHWbWCVLo1OLOtjyIQFf0cOUkVNc+zXloTafqcjCSzBWuFlinGrhPhZpdec7ZTC+JSd4mgD/RvfW1hdy72I2c/X6chCuJ/ZiVCaKKTCbkfB1YReqXzsvmypQBQLO1CiyP8k36yQA8HNRma2CV/o5IA5nQi9+kNswIDAQAB
-----END PUBLIC KEY-----"""
## 私钥的配置
app_private_key_string ="""-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAy1o2kzDLr8rXWVgtQ2HcaCXwlFyskx7V5PlWkRqqIqgVQQ7kiPw4Ru9PWou3fA5hBWCNQmJEgIBfGukdqoeitXcft1K5U5/gEOrUL8dqBf/VsN4iAwzptgfDXnC6UGz0NmOWihi6LtXftds7uMVNYAXHs3vf9TgJJusehVpkT7Evf+46VAKh7TnHWbWCVLo1OLOtjyIQFf0cOUkVNc+zXloTafqcjCSzBWuFlinGrhPhZpdec7ZTC+JSd4mgD/RvfW1hdy72I2c/X6chCuJ/ZiVCaKKTCbkfB1YReqXzsvmypQBQLO1CiyP8k36yQA8HNRma2CV/o5IA5nQi9+kNswIDAQABAoIBAQCTl0BxCENtrZ0rPXJsq4RbGt5H8BNZHFJGRCnuWxoM2U3D0FlSiy0VXu+LWkisA4uraW5dNhFd6s4cLAHaGWOgrXsZhTL5XNo1rRqgKu3quMqR+kdZS2/9LBlCXDL92HZPW2yRgmzvPU+HID1yV9FW1hshS9E6m5cY5iFazEZuB3JjBNbnKIDljvBHrqsrolZmSlROEzALJjC3w2s9wTwzMsdJx2+NyJg0t8qX7nDjRzBxEUvsvHQ9HpAyHWGP5E1yKR6CPaJEg7LnDJDL3cr1wecFd1IQA7X0i+KqFgnUd4k86PQ7tbq0q7bWRLNfcXHVUs4eORl9xXQP6zTccIYhAoGBAO3iQqmoc7GCXkqe1lis98RJJP00NYL/J5zwG/483Sfq7YjTXD1Ie+jno5gcgkqzEIOMooss6CPJVf7lyno6Z/NFLoYA4GGMPkyKn/83Ar4YxEr5eIdfrQFdroh+7uqP+ckPhvjmeA78cITTwvMWf446jRCfk5neaGPfV9OcTSnrAoGBANrWu/hIyon/aX9Xn2RqEB/sLzADkPLs7bIES+8V5mc3ieRjqzTWO1dgOiMlXdqsQKtGgHjTm21ZVMm2E9GvaaVQax197VX2+y7m5iFtUoQtDMQzdx5HXUFHhR24YedbSbkDrLjY5C/JsjuJCIR3LNiUkUdyR6YpOvR/1SqkzrFZAoGARpD094EZ+NFUiUw/B4Uf5qFQELCZIyfvp1Vu6GdDr6C4H/ubBC7pWvjEBc6HNAOUZYGlgiWrI1qJYRjnjISg64BdQbEm3qkMngYNWlcGQD/2kssYXwgZuSsCKEmHNBvLnEI35sPvX3qxIiXzUcsdwaJK0GCWF3Hrg5zwX7yhA0sCgYEAnQVW+l/AdCP/3o9Qnww7Zaxib2EfsC6wnvrWQUbFe2ouVuHtBoxxJ9Cz5mP5Y94UyNBdflTXQS7H17P9pIboluWM9ixVD0mYEZ87oOCARLbOYjlLTz6Fe0GGEj0qgobN7yLj2/5EPMXMTUuWAPZCB2USmOE259LNqoHOwjpe1IECgYBmaCV3SBB0GAktHAnSxabQLvQCrVWu65yROD/pJR1yRkLguhUES6jye+7LBSPAjbv/0vMpT7JhisaAT7piv/MYzzLJyTf+be1tYyzuqMtgHnS7sktc6jOmu09VZfDULbbLz2fS3YYckF/MqXiz7oQIXEsSVnRO1b+c9K1WGEPgnw==
-----END RSA PRIVATE KEY-----"""
appid = "2016101300673550"
## 实例化对象
alipay = AliPay(
        appid=appid,
        app_notify_url=None,
        app_private_key_string=app_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2",
        debug=False
)