# Generated by Django 2.2.1 on 2019-11-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='username',
        ),
    ]
