# Generated by Django 2.2.1 on 2019-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_loginuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=32, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='数量')),
                ('goods_location', models.TextField(verbose_name='生产地')),
                ('goods_safe_data', models.IntegerField(verbose_name='保质期')),
                ('goods_pro_time', models.DateField(auto_now=True, verbose_name='生产日期')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
