# Generated by Django 2.2.1 on 2019-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0005_goods_goods_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='address',
            field=models.TextField(default='beij'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(default='gtl.jpg', upload_to='img'),
        ),
    ]
