# Generated by Django 2.2.1 on 2019-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0006_auto_20191115_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True),
        ),
    ]
