# Generated by Django 2.2.1 on 2019-11-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, verbose_name='订单编号')),
                ('order_date', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '完成'), (6, '拒收')], verbose_name='订单状态')),
                ('order_total', models.FloatField(verbose_name='订单总价')),
                ('order_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.UserAddress', verbose_name='订单收货地址')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单表',
                'db_table': 'payorder',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('goods_count', models.IntegerField(verbose_name='订单商品数量')),
                ('goods_total_price', models.FloatField(verbose_name='商品小计')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '完成'), (6, '拒收')], default='1', verbose_name='订单详情状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
            ],
            options={
                'verbose_name': '订单详情表',
                'db_table': 'orderinfo',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_total', models.FloatField(verbose_name='单件商品的总价')),
                ('payorder', models.CharField(default='0', max_length=32, verbose_name='订单表的订单号')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', verbose_name='买家')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods', verbose_name='商品表外键')),
            ],
            options={
                'verbose_name': '购物车表',
                'db_table': 'cart',
            },
        ),
    ]
