# Generated by Django 2.2.1 on 2019-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payorder',
            field=models.IntegerField(default=0, verbose_name='订单表的订单号'),
        ),
    ]
