# Generated by Django 2.2.1 on 2019-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20191122_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='order_address',
            field=models.IntegerField(default=0, verbose_name='订单收货地址'),
        ),
    ]
