# Generated by Django 2.2.1 on 2019-11-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lebal', models.CharField(max_length=32)),
                ('type_description', models.TextField()),
                ('type_picture', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='gtl.jpg', upload_to='img')),
                ('user_type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='验证码内容')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='收货人手机号')),
                ('name', models.CharField(max_length=32, verbose_name='收货人名字')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=32, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='数量')),
                ('goods_location', models.TextField(verbose_name='生产地')),
                ('goods_safe_data', models.IntegerField(verbose_name='保质期')),
                ('goods_pro_time', models.DateField(auto_now=True, verbose_name='生产日期')),
                ('goods_status', models.IntegerField(default=1)),
                ('goods_picture', models.ImageField(default='img/gtl01.jpg', upload_to='img')),
                ('goods_description', models.TextField(default='good', verbose_name='商品描述')),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
