# Generated by Django 2.2.1 on 2019-11-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=32, verbose_name='商品编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_count', models.IntegerField(verbose_name='数量')),
                ('goods_location', models.TextField(verbose_name='生产地')),
                ('goods_safe_data', models.IntegerField(verbose_name='保质期')),
                ('goods_pro_time', models.DateField(auto_now=True, verbose_name='生产日期')),
                ('goods_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='gtl.jpg', upload_to='img')),
            ],
            options={
                'db_table': 'loginuser',
            },
        ),
    ]
