# Generated by Django 2.2.1 on 2019-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20191118_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(default='img/gtl01.jpg', upload_to='img'),
        ),
    ]
