# Generated by Django 2.2.1 on 2019-11-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_goods_goods_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.CharField(default='img/zhu.jpg', max_length=64),
            preserve_default=False,
        ),
    ]
