# Generated by Django 2.2.1 on 2019-11-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomeNew',
        ),
    ]
