# Generated by Django 2.2.1 on 2019-11-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191105_1512'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homenew',
            table='homenew',
        ),
    ]
