# Generated by Django 2.2.1 on 2019-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
