# Generated by Django 2.2.1 on 2019-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_user_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='width2',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
