# Generated by Django 2.2.1 on 2019-11-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_user_width2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='width2',
        ),
    ]
