# Generated by Django 2.2.1 on 2019-11-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20191105_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(auto_now=True, verbose_name='生日'),
        ),
    ]
