# Generated by Django 2.2.1 on 2019-11-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20191106_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
