# Generated by Django 2.2.1 on 2019-11-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_user_now_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='now_time',
        ),
    ]
