# Generated by Django 2.2.1 on 2019-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_user_now_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
