# Generated by Django 2.2.1 on 2019-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_user_now_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2019-02-01', verbose_name='生日'),
        ),
    ]
