# Generated by Django 2.2.1 on 2019-11-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_book_publish'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='publish',
            table='publish',
        ),
    ]
