# Generated by Django 2.2.1 on 2019-11-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20191106_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Publish'),
            preserve_default=False,
        ),
    ]
