# Generated by Django 2.2.1 on 2019-11-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_person_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
