# Generated by Django 2.2.1 on 2019-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20191107_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.ManyToManyField(to='app01.Person'),
        ),
    ]
