# Generated by Django 2.2.1 on 2019-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_teacher_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=100, verbose_name='库存量'),
        ),
        migrations.AddField(
            model_name='book',
            name='sell_num',
            field=models.IntegerField(default=100, verbose_name='已售数量'),
        ),
    ]
